//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banco.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Traducoes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Traducoes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Banco.resources.Traducoes", typeof(Traducoes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Seu novo saldo da sua conta é: [{1}].
        /// </summary>
        internal static string @__0___SEU_NOVO_SALDO_DA_SUA_CONTA_É____1__ {
            get {
                return ResourceManager.GetString("[{0}]_SEU_NOVO_SALDO_DA_SUA_CONTA_É:_[{1}]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  1 - Listar todas as contas .
        /// </summary>
        internal static string _1_LISTAR_TODAS_AS_CONTAS {
            get {
                return ResourceManager.GetString("1-LISTAR_TODAS_AS_CONTAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  2 - Criar nova conta .
        /// </summary>
        internal static string _2_CRIAR_NOVA_CONTA {
            get {
                return ResourceManager.GetString("2-CRIAR_NOVA_CONTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  3 - Transferir .
        /// </summary>
        internal static string _3_TRANSFERIR {
            get {
                return ResourceManager.GetString("3-TRANSFERIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  4 - Sacar .
        /// </summary>
        internal static string _4_SACAR {
            get {
                return ResourceManager.GetString("4-SACAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  5 - Depositar .
        /// </summary>
        internal static string _5_DEPOSITAR {
            get {
                return ResourceManager.GetString("5-DEPOSITAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Aplicação finalizada com sucesso .
        /// </summary>
        internal static string APLICACAO_FINALIZADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("APLICACAO_FINALIZADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Contas cadastradas .
        /// </summary>
        internal static string CONTAS_CADASTRADAS {
            get {
                return ResourceManager.GetString("CONTAS_CADASTRADAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Criar nova conta .
        /// </summary>
        internal static string CRIAR_NOVA_CONTA {
            get {
                return ResourceManager.GetString("CRIAR_NOVA_CONTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Depositar valor .
        /// </summary>
        internal static string DEPOSITAR_VALOR {
            get {
                return ResourceManager.GetString("DEPOSITAR_VALOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Digite 1 para conta fisica ou 2 para conta juridica: .
        /// </summary>
        internal static string DIGITE_1_PARA_PESSOA_FISICA_OU_2_PARA_PESSOA_JURIDICA {
            get {
                return ResourceManager.GetString("DIGITE_1_PARA_PESSOA_FISICA_OU_2_PARA_PESSOA_JURIDICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Digite o ID da conta .
        /// </summary>
        internal static string DIGITE_O_ID_DA_CONTA {
            get {
                return ResourceManager.GetString("DIGITE_O_ID_DA_CONTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Digite o ID da conta origem: .
        /// </summary>
        internal static string DIGITE_O_ID_DA_CONTA_DE_ORIGEM {
            get {
                return ResourceManager.GetString("DIGITE_O_ID_DA_CONTA_DE_ORIGEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Digite o ID da conta destino: .
        /// </summary>
        internal static string DIGITE_O_ID_DA_CONTA_DESTINO {
            get {
                return ResourceManager.GetString("DIGITE_O_ID_DA_CONTA_DESTINO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Digite o saldo inicial: .
        /// </summary>
        internal static string DIGITE_O_SALDO_INICIAL {
            get {
                return ResourceManager.GetString("DIGITE_O_SALDO_INICIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Digite o valor a ser depositado na conta: .
        /// </summary>
        internal static string DIGITE_O_VALOR_A_SER_DEPOSITADO_NA_CONTA {
            get {
                return ResourceManager.GetString("DIGITE_O_VALOR_A_SER_DEPOSITADO_NA_CONTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Digite o valor a ser sacado da conta: .
        /// </summary>
        internal static string DIGITE_O_VALOR_A_SER_SACADO_DA_CONTA {
            get {
                return ResourceManager.GetString("DIGITE_O_VALOR_A_SER_SACADO_DA_CONTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Digite o valor a ser transferido: .
        /// </summary>
        internal static string DIGITE_O_VALOR_A_SER_TRANSFERIDO {
            get {
                return ResourceManager.GetString("DIGITE_O_VALOR_A_SER_TRANSFERIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Digite o seu nome: .
        /// </summary>
        internal static string DIGITE_SEU_NOME {
            get {
                return ResourceManager.GetString("DIGITE_SEU_NOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Entre com a opção desejada: .
        /// </summary>
        internal static string ENTRE_COM_A_OPCAO_DESEJADA {
            get {
                return ResourceManager.GetString("ENTRE_COM_A_OPCAO_DESEJADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entre com seu crédito disponível: .
        /// </summary>
        internal static string ENTRE_COM_SEU_CREDITO_DISPONIVEL {
            get {
                return ResourceManager.GetString("ENTRE_COM_SEU_CREDITO_DISPONIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc para Voltar...
        /// </summary>
        internal static string ESC_PARA_VOLTAR__ {
            get {
                return ResourceManager.GetString("ESC_PARA_VOLTAR..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Nenhum usuário cadastrado! .
        /// </summary>
        internal static string NENHUM_USUARIO_CADASTRADO {
            get {
                return ResourceManager.GetString("NENHUM_USUARIO_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOME: .
        /// </summary>
        internal static string NOME__ {
            get {
                return ResourceManager.GetString("NOME: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Sacar valor .
        /// </summary>
        internal static string SACAR_VALOR {
            get {
                return ResourceManager.GetString("SACAR_VALOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALDO: .
        /// </summary>
        internal static string SALDO__ {
            get {
                return ResourceManager.GetString("SALDO: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIPO DE CONTA: .
        /// </summary>
        internal static string TIPO_DE_CONTA__ {
            get {
                return ResourceManager.GetString("TIPO_DE_CONTA: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferencia concluída com sucesso para [{0}], o novo saldo é de: [{1}].
        /// </summary>
        internal static string TRANSFERENCIA_CONCLUIDA_COM_SUCESSO_PARA___0____O_NOVO_SALDO_É_DE____1__ {
            get {
                return ResourceManager.GetString("TRANSFERENCIA_CONCLUIDA_COM_SUCESSO_PARA_[{0}],_O_NOVO_SALDO_É_DE:_[{1}]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Transferir valor .
        /// </summary>
        internal static string TRANSFERIR_VALOR {
            get {
                return ResourceManager.GetString("TRANSFERIR_VALOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  X - Sair .
        /// </summary>
        internal static string X_SAIR {
            get {
                return ResourceManager.GetString("X-SAIR", resourceCulture);
            }
        }
    }
}
